services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "9000:9000"
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
      - /app/tmp
      - /app/bin
      - /app/web/node_modules
      - /app/web/dist
      - go-modules:/go/pkg/mod
    environment:
      - DATABASE_URL=${DATABASE_URL:-}
    working_dir: /app
    command: sh -c "cd /app/web && npm install && npm run build && cd /app && air -c .air.toml"

volumes:
  go-modules:
